apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: strimzi-kafka-operator
  namespace: openshift-operators
spec:
  channel: strimzi-0.19.x
  name: strimzi-kafka-operator
  source: community-operators
  sourceNamespace: openshift-marketplace