dependencies:
  - name: humio-core
    version: 0.1.2
    repository: file://./charts/humio-core
    condition: humio-core.enabled
  - name: humio-strix
    version: 0.1.0
    repository: file://./charts/humio-strix
    condition: humio-strix.enabled
  - name: humio-fluentbit
    version: 0.1.0
    repository: file://./charts/humio-fluentbit
    condition: humio-fluentbit.enabled
  - name: humio-metrics
    version: 0.1.0
    repository: file://./charts/humio-metrics
    condition: humio-metrics.enabled
