# Deployments
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "bookinfo","availableReplicas": 1,"createdReplicas": 1,"dataCenter": "demo","desiredReplicas": 1,"entityTypes": ["deployment"],"matchTokens": ["productpage-v1"],"name": "productpage-v1","namespace": "bookinfo","readyReplicas": 1,"tags": ["app:productpage","namespace:bookinfo"],"vertexType": "resource","uniqueId": "productpage-v1"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "bookinfo","availableReplicas": 1,"createdReplicas": 1,"dataCenter": "demo","desiredReplicas": 1,"entityTypes": ["deployment"],"matchTokens": ["reviews-v1"],"name": "reviews-v1","namespace": "bookinfo","readyReplicas": 1,"tags": ["app:productpage","namespace:bookinfo"],"vertexType": "resource","uniqueId": "reviews-v1"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "bookinfo","availableReplicas": 1,"createdReplicas": 1,"dataCenter": "demo","desiredReplicas": 1,"entityTypes": ["deployment"],"matchTokens": ["reviews-v2"],"name": "reviews-v2","namespace": "bookinfo","readyReplicas": 1,"tags": ["app:productpage","namespace:bookinfo"],"vertexType": "resource","uniqueId": "reviews-v2"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "bookinfo","availableReplicas": 1,"createdReplicas": 1,"dataCenter": "demo","desiredReplicas": 1,"entityTypes": ["deployment"],"matchTokens": ["reviews-v3"],"name": "reviews-v3","namespace": "bookinfo","readyReplicas": 1,"tags": ["app:productpage","namespace:bookinfo"],"vertexType": "resource","uniqueId": "reviews-v3"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "bookinfo","availableReplicas": 1,"createdReplicas": 1,"dataCenter": "demo","desiredReplicas": 1,"entityTypes": ["deployment"],"matchTokens": ["details-v1"],"name": "details-v1","namespace": "bookinfo","readyReplicas": 1,"tags": ["app:productpage","namespace:bookinfo"],"vertexType": "resource","uniqueId": "details-v1"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "bookinfo","availableReplicas": 1,"createdReplicas": 1,"dataCenter": "demo","desiredReplicas": 1,"entityTypes": ["deployment"],"matchTokens": ["ratings-v1"],"name": "ratings-v1","namespace": "bookinfo","readyReplicas": 1,"tags": ["app:productpage","namespace:bookinfo"],"vertexType": "resource","uniqueId": "ratings-v1"}'

curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "connectedTo","_fromUniqueId": "productpage-v1","_toUniqueId": "details-v1"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "connectedTo","_fromUniqueId": "productpage-v1","_toUniqueId": "reviews-v1"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "connectedTo","_fromUniqueId": "productpage-v1","_toUniqueId": "reviews-v2"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "connectedTo","_fromUniqueId": "productpage-v1","_toUniqueId": "reviews-v3"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "connectedTo","_fromUniqueId": "reviews-v2","_toUniqueId": "ratings-v1"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "connectedTo","_fromUniqueId": "reviews-v3","_toUniqueId": "ratings-v1"}'



# Pods
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "bookinfo","dataCenter": "demo","entityTypes": ["pod"],"matchTokens": ["productpage-v1-pod"],"name": "productpage-v1-pod","namespace": "bookinfo","readyReplicas": 1,"tags": ["app:productpage","namespace:bookinfo"],"vertexType": "resource","uniqueId": "productpage-v1-pod"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "bookinfo","dataCenter": "demo","entityTypes": ["pod"],"matchTokens": ["reviews-v1-pod"],"name": "reviews-v1-pod","namespace": "bookinfo","readyReplicas": 1,"tags": ["app:productpage","namespace:bookinfo"],"vertexType": "resource","uniqueId": "reviews-v1-pod"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "bookinfo","dataCenter": "demo","entityTypes": ["pod"],"matchTokens": ["reviews-v2-pod"],"name": "reviews-v2-pod","namespace": "bookinfo","readyReplicas": 1,"tags": ["app:productpage","namespace:bookinfo"],"vertexType": "resource","uniqueId": "reviews-v2-pod"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "bookinfo","dataCenter": "demo","entityTypes": ["pod"],"matchTokens": ["reviews-v3-pod"],"name": "reviews-v3-pod","namespace": "bookinfo","readyReplicas": 1,"tags": ["app:productpage","namespace:bookinfo"],"vertexType": "resource","uniqueId": "reviews-v3-pod"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "bookinfo","dataCenter": "demo","entityTypes": ["pod"],"matchTokens": ["details-v1-pod"],"name": "details-v1-pod","namespace": "bookinfo","readyReplicas": 1,"tags": ["app:productpage","namespace:bookinfo"],"vertexType": "resource","uniqueId": "details-v1-pod"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "bookinfo","dataCenter": "demo","entityTypes": ["pod"],"matchTokens": ["ratings-v1-pod"],"name": "ratings-v1-pod","namespace": "bookinfo","readyReplicas": 1,"tags": ["app:productpage","namespace:bookinfo"],"vertexType": "resource","uniqueId": "ratings-v1-pod"}'


curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "manages","_fromUniqueId": "productpage-v1","_toUniqueId": "productpage-v1-pod"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "manages","_fromUniqueId": "reviews-v1","_toUniqueId": "reviews-v1-pod"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "manages","_fromUniqueId": "reviews-v2","_toUniqueId": "reviews-v2-pod"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "manages","_fromUniqueId": "reviews-v3","_toUniqueId": "reviews-v3-pod"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "manages","_fromUniqueId": "ratings-v1","_toUniqueId": "ratings-v1-pod"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "manages","_fromUniqueId": "details-v1","_toUniqueId": "details-v1-pod"}'



# Services
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "bookinfo","dataCenter": "demo","entityTypes": ["service"],"matchTokens": ["productpage-v1-svc"],"name": "productpage-v1-svc","namespace": "bookinfo","readyReplicas": 1,"tags": ["app:productpage","namespace:bookinfo"],"vertexType": "resource","uniqueId": "productpage-v1-svc"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "bookinfo","dataCenter": "demo","entityTypes": ["service"],"matchTokens": ["reviews-v1-svc"],"name": "reviews-v1-svc","namespace": "bookinfo","readyReplicas": 1,"tags": ["app:productpage","namespace:bookinfo"],"vertexType": "resource","uniqueId": "reviews-v1-svc"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "bookinfo","dataCenter": "demo","entityTypes": ["service"],"matchTokens": ["reviews-v2-svc"],"name": "reviews-v2-svc","namespace": "bookinfo","readyReplicas": 1,"tags": ["app:productpage","namespace:bookinfo"],"vertexType": "resource","uniqueId": "reviews-v2-svc"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "bookinfo","dataCenter": "demo","entityTypes": ["service"],"matchTokens": ["reviews-v3-svc"],"name": "reviews-v3-svc","namespace": "bookinfo","readyReplicas": 1,"tags": ["app:productpage","namespace:bookinfo"],"vertexType": "resource","uniqueId": "reviews-v3-svc"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "bookinfo","dataCenter": "demo","entityTypes": ["service"],"matchTokens": ["details-v1-svc"],"name": "details-v1-svc","namespace": "bookinfo","readyReplicas": 1,"tags": ["app:productpage","namespace:bookinfo"],"vertexType": "resource","uniqueId": "details-v1-svc"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "bookinfo","dataCenter": "demo","entityTypes": ["service"],"matchTokens": ["ratings-v1-svc"],"name": "ratings-v1-svc","namespace": "bookinfo","readyReplicas": 1,"tags": ["app:productpage","namespace:bookinfo"],"vertexType": "resource","uniqueId": "ratings-v1-svc"}'



curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "manages","_fromUniqueId": "productpage-v1-pod","_toUniqueId": "productpage-v1-svc"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "manages","_fromUniqueId": "reviews-v1-pod","_toUniqueId": "reviews-v1-svc"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "manages","_fromUniqueId": "reviews-v2-pod","_toUniqueId": "reviews-v2-svc"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "manages","_fromUniqueId": "reviews-v3-pod","_toUniqueId": "reviews-v3-svc"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "manages","_fromUniqueId": "ratings-v1-pod","_toUniqueId": "ratings-v1-svc"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "manages","_fromUniqueId": "details-v1-pod","_toUniqueId": "details-v1-svc"}'


