apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: zen-op-group
spec:
  targetNamespaces:
    - zen
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-watson-aiops
spec:
  channel: v1.1
  installPlanApproval: Automatic
  name: ibm-watson-aiops
  source: ibm-watson-aiops-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: ibm-watson-aiops-operator.v1.1.0
