{{- if and (or .Values.cache.localVolume.enabled (eq .Values.primaryStorage.type "local")) .Values.cache.localVolume.enableLocalVolumeProvisioner -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
{{- if eq .Values.primaryStorage.type "local" }}
  name: {{ .Values.localVolume.name }}
{{- else if .Values.cache.localVolume.enabled }}
  name: {{ .Values.cache.localVolume.name }}
{{- end }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
{{- end -}}
