{{- if and (or .Values.cache.localVolume.enabled (eq .Values.primaryStorage.type "local")) .Values.cache.localVolume.enableLocalVolumeProvisioner -}}
{{- if .Capabilities.APIVersions.Has "apps/v1" }}
apiVersion: apps/v1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: DaemonSet
metadata:
  name: local-volume-provisioner
  namespace: {{ .Release.Namespace }}
  labels:
    app: local-volume-provisioner
    chart: {{ template "humio-core.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: local-volume-provisioner
  template:
    metadata:
      labels:
        app: local-volume-provisioner
    spec:
      serviceAccountName: local-storage-admin
      containers:
        - image: "quay.io/external_storage/local-volume-provisioner:v2.3.2"
          name: provisioner
          securityContext:
            privileged: true
          env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: JOB_CONTAINER_IMAGE
            value: "quay.io/external_storage/local-volume-provisioner:v2.3.2"
          volumeMounts:
            - name: provisioner-config
              mountPath: /etc/provisioner/config
              readOnly: true
            - name: provisioner-dev
              mountPath: /dev
            - name: local-storage-mount
              mountPropagation: "HostToContainer"
            {{- if eq .Values.primaryStorage.type "local" }}
              mountPath: {{ .Values.localVolume.hostPath }}
            {{- else if .Values.cache.localVolume.enabled }}
              mountPath: {{ .Values.cache.localVolume.hostPath }}
            {{- end }}
      volumes:
        - name: provisioner-config
          configMap:
            name: local-provisioner-config
        - name: provisioner-dev
          hostPath:
            path: /dev
        - name: local-storage-mount
          hostPath:
          {{- if eq .Values.primaryStorage.type "local" }}
            path: {{ .Values.localVolume.hostPath }}
          {{- else if .Values.cache.localVolume.enabled }}
            path: {{ .Values.cache.localVolume.hostPath }}
          {{- end }}
{{- end -}}
