# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ include "humio-core.fullname" . }}-nodeport
#   labels:
#     app: {{ template "humio-core.name" . }}
#     chart: {{ template "humio-core.chart" . }}
#     release: {{ .Release.Name }}
#     heritage: {{ .Release.Service }}
# spec:
#   type: {{ .Values.service.type }}
#   ports:
#     - port: 30080
#       targetPort: 8080
#       name: httpnodeport
#       nodeport: 30080
#   selector:
#     app: {{ include "humio-core.name" . }}
#     release: {{ .Release.Name }}
