apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ default "default" .Release.Namespace }}
  name: {{ .Release.Name }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create"]
- apiGroups: [""]
  resources:
  - pods
  verbs: ["get", "list", "watch"]
