apiVersion: v1
kind: Secret
metadata:
  name: developer-user-password
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  password: {{ randAlphaNum 24 | b64enc | quote }}
