{{- if .Values.token }}
apiVersion: v1
kind: Secret
metadata:
  name: fluentbit-custom-token
  annotations:
    "helm.sh/hook": "pre-install"
type: Opaque
data:
  {{ .Values.tokenSecretKeyName }}: {{ .Values.token | b64enc | quote }}
{{- end }}
