apiVersion: watson-aiops.ibm.com/v1beta1
kind: AIManager
metadata:
  name: ai-manager-test
  namespace: zen
spec:
  existingPullSecret:
    name: cp.stg.icr.io
  flink:
    storage:
      enabled: true
      storageClassName: ''
      storageSize: 1Gi
    taskmanager:
      replicas: 1
      taskmanagerSlots: 12
  size: small
  license:
    accept: true
  zen:
    storage:
      storageClassName: ''
  kafka:
    autoTopicCreation: false
    storage:
      enabled: true
      storageClassName: ''
      storageSize: 20Gi
  repo: ''
  version: 2.1.0
  minio:
    storage:
      storageClassName: ''
      storageSize: 100Gi
      enabled: true
  aimanagerValues:
    postgres:
      livenessProbe:
        initialDelaySeconds: 300
        timeoutSeconds: 15
        failureThreshold: 5
        periodSeconds: 15
        successThreshold: 1
      readinessProbe:
        initialDelaySeconds: 300
        timeoutSeconds: 15
        failureThreshold: 5
        periodSeconds: 15
        successThreshold: 1
      keeper:
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      sentinel:
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
  postgres:
    storage:
      enabled: true
      storageClassName: ''
      storageSize: 20Gi
  storage:
    enabled: true
    storageClassName: ibmc-file-gold-gid
  elasticsearch:
    storage:
      enabled: true
      storageClassName: ''
      storageSize: 100Gi
  modelTrain:
    maxLearners: 2
    pollInterval: 60
    sizeLimit: 1000
