kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongodb
  namespace: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongodb
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: mongodb
    spec:
      containers:
        - name: mongodb
          image: 'robotshop/rs-mongodb:latest'
          ports:
            - containerPort: 27017
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 25Mi
            requests:
              cpu: 100m
              memory: 10Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: robot-shop
      serviceAccount: robot-shop
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
