{{- if eq .Values.clusterIdentity.type "zookeeper" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: {{ default "default" .Release.Namespace }}
  name: {{ .Release.Name }}
rules:
- apiGroups: [""]
  resources:
  - nodes
  verbs: ["get", "list", "watch"]
{{- end -}}
