apiVersion: v1
kind: Service
metadata:
  name: "{{ include "humio-core.fullname" . }}-es"
  labels:
    app: {{ template "humio-core.name" . }}
    chart: {{ template "humio-core.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.es_port }}
      targetPort: es
      protocol: TCP
      name: esclust
  selector:
    app: {{ include "humio-core.name" . }}
    release: {{ .Release.Name }}
