apiVersion: v1
kind: Service
metadata:
  name: {{ include "humio-core.fullname" . }}-http
  labels:
    app: {{ template "humio-core.name" . }}
    chart: {{ template "humio-core.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{ if .Values.openshift.host }}
    inmenu: "true"
    target: "Humio"
  annotations:
    name: "Humio"
    id: "administer-mcm"
    roles: "ClusterAdministrator,Administrator,Operator,Viewer"
    url: http://{{ include "routepath" (list . ) }}
{{ end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http_port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "humio-core.name" . }}
    release: {{ .Release.Name }}
