{{- if and (or .Values.cache.localVolume.enabled (eq .Values.primaryStorage.type "local")) .Values.cache.localVolume.enableLocalVolumeProvisioner -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-storage-admin
  namespace: {{ .Release.Namespace }}
{{- end -}}
