{{- if .Values.global -}}
{{- if .Values.global.sharedTokens }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-create-shared-tokens"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ .Release.Name }}-post-install
      initContainers:
        - name: wait-for-humio
          image: "{{ default "humio/strix" .Values.strixImage }}"
          imagePullPolicy: {{ .Values.strixImagePullPolicy }}
          command:
          - kubectl
          - wait
          - "--for=condition=Ready"
          - "pod/{{ .Release.Name }}-humio-core-0"
          - "-n"
          - {{ .Release.Namespace }}
          - "--timeout=1500s"
        - name: wait-for-single-user-token
          image: "{{ default "humio/strix" .Values.strixImage }}"
          imagePullPolicy: {{ .Values.strixImagePullPolicy }}
          command:
          - kubectl
          - wait
          - "--for=condition=Complete"
          - "job/{{ .Release.Name }}-create-single-user-token"
          - "-n"
          - {{ .Release.Namespace }}
          - "--timeout=1500s"
      containers:
        - name: humio-init
          image: "{{ .Values.initImage }}"
          imagePullPolicy: {{ .Values.initImagePullPolicy }}
          command: ["/humio-init.sh"]
          env:
            - name: HUMIO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: developer-user-token
                  key: token
            - name: HUMIO_ADDRESS
            {{- if .Values.baseUrl }}
              value: "{{ .Values.baseUrl }}/"
            {{- else }}
              value: "http://{{ .Release.Name }}-humio-core-headless:8080/"
            {{- end}}
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SHARED_TOKENS
              value: "
              {{- range $index, $tokenData := .Values.global.sharedTokens -}}
                {{- range $repo, $token := $tokenData -}}
                  {{- $index -}}-shared-token:{{- $repo }}:{{- $token -}},
                {{- end }}
              {{- end -}}
              "
{{- end }}
{{- end }}
