apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-post-install
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-post-install
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-post-install
  namespace: {{ default "default" .Release.Namespace }}
