# apiVersion: v1
# kind: Service
# metadata:
#   name: "{{ include "humio-core.fullname" . }}-tcp-lb"
#   labels:
#     app: {{ include "humio-core.name" . }}
#     release: {{ .Release.Name }}
# spec:
#   type: LoadBalancer
#   ports:
#     - port: {{ .Values.service.es_port }}
#       targetPort: es
#       protocol: TCP
#       name: tcplb
#   selector:
#     app: {{ include "humio-core.name" . }}
#     release: {{ .Release.Name }}
