apiVersion: watson-aiops.ibm.com/v1beta1
kind: NOI
metadata:
  name: demo-noi
  namespace: <NAMESPACE>
spec:
  license:
    accept: true
  advanced:
    antiAffinity: false
    imagePullPolicy: IfNotPresent
    imagePullRepository: cp.icr.io/cp/noi
  ldap:
    port: '389'
    mode: standalone
    userFilter: 'uid=%s,ou=users'
    bindDN: 'cn=admin,dc=mycluster,dc=icp'
    sslPort: '636'
    url: 'ldap://localhost:389'
    suffix: 'dc=mycluster,dc=icp'
    groupFilter: 'cn=%s,ou=groups'
    baseDN: 'dc=mycluster,dc=icp'
    storageSize: 1Gi
    serverType: CUSTOM
    storageClass: '<STORAGE_CLASS>'
  backupRestore:
    enableAnalyticsBackups: false
  topology:
    enabled: true
    storageClassElasticTopology: '<STORAGE_CLASS>'
    storageSizeElasticTopology: 75Gi
    storageSizeFileObserver: 5Gi
    storageClassFileObserver: '<STORAGE_CLASS>'
    appDisco:
      enabled: false
      scaleSSS: '1'
      tlsSecret: ''
      dbsecret: ''
      db2database: taddm
      dburl: ''
      certSecret: ''
      db2archuser: archuser
      secure: false
      scaleDS: '1'
      db2user: db2inst1
      dbport: '50000'
    observers:
      docker: false
      taddm: false
      servicenow: false
      ibmcloud: false
      alm: false
      contrail: false
      cienablueplanet: false
      kubernetes: true
      bigfixinventory: false
      junipercso: false
      dns: false
      itnm: false
      ansibleawx: false
      ciscoaci: false
      azure: false
      rancher: false
      newrelic: false
      vmvcenter: false
      rest: true
      appdynamics: false
      jenkins: false
      zabbix: false
      file: false
      googlecloud: false
      dynatrace: false
      aws: false
      openstack: false
      vmwarensx: false
    netDisco: false
  version: 1.6.3
  entitlementSecret: cp.stg.icr.io
  clusterDomain: >-
    <CLUSTER_FQDN>
  integrations:
    humio:
      repository: ''
      url: ''
  persistence:
    storageSizeNCOBackup: 5Gi
    enabled: true
    storageSizeNCOPrimary: 5Gi
    storageClassNCOPrimary: '<STORAGE_CLASS>'
    storageSizeImpactServer: 5Gi
    storageClassImpactServer: '<STORAGE_CLASS>'
    storageClassKafka: '<STORAGE_CLASS>'
    storageSizeKafka: 50Gi
    storageClassCassandraBackup: '<STORAGE_CLASS>'
    storageSizeCassandraBackup: 50Gi
    storageClassZookeeper: '<STORAGE_CLASS>'
    storageClassCouchdb: '<STORAGE_CLASS>'
    storageSizeZookeeper: 5Gi
    storageSizeCouchdb: 20Gi
    storageClassCassandraData: '<STORAGE_CLASS>'
    storageSizeCassandraData: 50Gi
    storageClassDB2: '<STORAGE_CLASS>'
    storageClassElastic: '<STORAGE_CLASS>'
    storageSizeDB2: 5Gi
    storageClassImpactGUI: '<STORAGE_CLASS>'
    storageSizeImpactGUI: 5Gi
    storageSizeElastic: 75Gi
    storageClassNCOBackup: '<STORAGE_CLASS>'
  deploymentType: trial
